barrucadu/nixfiles

.github/workflows/ci.yaml

It would be nice if changes to actions caused some sort of automatic
validation check, which would have failed #5

Fix GitHub Actions config

---

common.nix
hosts/carcosa/configuration.nix
hosts/carcosa/hardware.nix
hosts/dreamlands/configuration.nix
hosts/dunwich/configuration.nix

This is a new, larger, machine which will absorb dunwich, dreamlands,
and some of lainon.life.  It's also in Hetzner Cloud, and is in the
erase-your-darlings style.

Add basic config for carcosa

---

hosts/nyarlathotep/grafana-dashboards/overview.json
hosts/nyarlathotep/hardware.nix

There's a bunch of unrelated changes to the grafana dashboard: the
only "real" change there is adding `/var/log` to the disk space
panels.

[nyarlathotep] Add a persistent /var/log volume

---

hosts/carcosa/configuration.nix
hosts/lainonlife/configuration.nix

I started by just [opting out of FLoC](https://github.com/WICG/floc/blob/main/README.md#opting-out-of-computation), but ended up adding a bunch more.

Set up Caddy security headers

---

hosts/nyarlathotep/grafana-dashboards/finance.json

- drop food (because I never save up in this, and if I lost income I'd
take money from float or emergency)
- increase graze, household, patreon, rent, roll20
All the targets are now at least 4 months expenses (some significantly
more, like health or gift) rounded up to a nice number.

[nyarlathotep]  Revise all budget targets

---

hosts/azathoth/configuration.nix
services/pleroma.nix

For each machine, clone this branch, try upgrading, fix any errors (& push a commit), and reboot.

Upgrade to NixOS 21.05

---

hosts/nyarlathotep/grafana-dashboards/finance.json

This is way too high, I normally spend a few pounds a month at most on
toothpaste and mouthwash.  I've left it as high as it now is because
there are occasional big purchases, like new glasses.

[nyarlathotep] Drop health budget

---

hosts/nyarlathotep/grafana-dashboards/finance.json

I will be travelling to and from the office significantly less when I
do return.

[nyarlathotep] Revise travel budget threshold

---

hosts/nyarlathotep/grafana-dashboards/finance.json

According to The Millionaire Next Door, a person's expected net
worth (sans inheritance) is:
```
pre-tax income sans inheritance * age / 10
```
People with under half of that are UAWs (underaccumulators of wealth),
people with more than double that are PAWs (prodigious accumulators of
wealth), and everyone else is an AAW (average accumulator of wealth).
So, add these thresholds to the assets graph.
First, I've worked out average daily income sans gifts, which I'm
using as a stand-in for inheritance here.  They're kind of the same
thing: money I've received for nothing, rather than earned from work
or an investment.
```
(-(last("income[£]") - first("income[£]") + last("income:gift[£]") - first("income:gift[£]")) / count("income[£]"))
```
Remember that income is negative: hence the signs! …

[nyarlathotep] Add AAW, PAW, and FIRE thresholds to assets graph

---

common.nix
hosts/carcosa/configuration.nix
hosts/lainonlife/configuration.nix
hosts/lainonlife/service-radio.nix
services/minecraft.nix

Upgrade to NixOS 21.11

---

services/resolved.nix

The unit had a couple of problems:
- It didn't start on boot
- It didn't have the reload command
And resolved had one major bug:
- It couldn't resolve names using Cloudflare DNS
All fixed now.

Upgrade to latest version of resolved & fix a couple of issues with unit

---

hosts/nyarlathotep/configuration.nix
hosts/nyarlathotep/grafana-dashboards/dns-resolver.json
services/resolved.nix

This requires upgrading to the latest version of resolved, which adds Prometheus metrics.

[nyarlathotep] Add a DNS dashboard

---

hosts/nyarlathotep/configuration.nix

It's now a Go program, so I can just compile and run it without
needing to worry about Python dependencies.

[nyarlathotep] Use new non-dockerised prometheus-awair-exporter

---

hosts/carcosa/memo-barrucadu-co-uk.caddyfile

These have been moved to my personal wiki.

[carcosa] Serve 410 responses for some memos

---

hosts/nyarlathotep/configuration.nix

In the 3 years since I last updated flood, the project has been
abandoned by the original developer, taken over by someone else, given
command-line arguments for all the options I care about, and been put
in nixpkgs.
Sometimes, laziness pays off.

[nyarlathotep] Switch to nixpkgs version of flood

---

hosts/nyarlathotep/jobs/hledger-export-to-promscale.py

For each account:
- Whenever money is added, insert it into a new bucket
- Whenever money is removed, take it from the oldest bucket
Then report the age of the oldest nonempty bucket.  That's age-of-money.
I haven't added this metric to the dashboard.  I think it has some uses---eg, since I aim to have ~3 months expenses saved up, when reviewing budget goals one thing I can check is whether the money I currently have allocated for a goal significantly older / younger than the target---but I think adding one panel for each budget category would be too much noise, and adding a high-level AoM for, say, `assets:cash` would (1) not be very interesting since I invest my excess income rather than keep it in the bank (so the number is pretty static), and (2) maybe even encourage me to invest …

[nyarlathotep] Export age-of-money metric to Promscale

---

hosts/nyarlathotep/grafana-dashboards/finance.json
hosts/nyarlathotep/jobs/hledger-fetch-fx-rates.py

I haven't had any crypto for upwards of 2 years at this point, I don't
need these rates.

[nyarlathotep] Remove crypto from FX fetcher script and dashboard

---

common.nix
hosts/carcosa/configuration.nix
hosts/lainonlife/configuration.nix
hosts/nyarlathotep/configuration.nix

There are no backwards incompatibilities which make bumping the
stateVersion unsafe.

Upgrade to NixOS 22.05

---

common.nix

Fix auto-upgrade channel version

---

hosts/lainonlife/configuration.nix
hosts/lainonlife/service-radio.nix
hosts/nyarlathotep/jobs/hledger-export-to-promscale.py
services/minecraft.nix

This is useful to avoid needing to fill in fake FX rates when
forecasting.

[nyarlathotep] Project forward FX rates if there are txns

---

hosts/nyarlathotep/grafana-dashboards/finance.json

[nyarlathotep] Finance dashboard tweaks

---

hosts/nyarlathotep/configuration.nix
services/bookdb.nix
services/bookmarks.nix
services/concourse.nix
services/finder.nix
services/pleroma.nix
services/umami.nix
services/wikijs.nix

Remove work-around for nixpkgs#104750

---

hosts/nyarlathotep/grafana-dashboards/smart-home.json

Using the celcius formula from wikipedia.

[nyarlathotep] Add heat index panel to smart home dashboard

---

hosts/nyarlathotep/configuration.nix

I never look at these metrics.

[nyarlathotep] Remove prometheus-speedtest-exporter

---

flake.lock
hosts/nyarlathotep/grafana-dashboards/finance.json

I renamed these for consistency with other accounts.

[nyarlathotep] Fix starling account names on dashboard 

---

hosts/nyarlathotep/grafana-dashboards/finance.json

This affects the AAW and PAW calculations.

[nyarlathotep] Update $age on finance dashboard

---

flake.lock
hosts/carcosa/configuration.nix
hosts/carcosa/secrets.yaml

I don't really use this any more, it's just taking up resources.
Publishing memo updates over activitypub was a neat idea, but RSS is
just easier.

[carcosa] Remove pleroma

---

flake.lock
hosts/carcosa/configuration.nix
hosts/carcosa/secrets.yaml

I use this when writing memos and weeknotes, but occasionally links to
it end up in the wild and that's kind of a pain.  So password-protect
it.
Also, since this is just for temporary previews, wipe the files after a
day.

[carcosa] Add config for misc/_site

---

flake.lock
shared/default.nix

See also https://github.com/barrucadu/dotfiles/commit/93c4bc5e8f810206c789729cad4103b97c289baf

Install `atuin`

---

shared/resolved/default.nix

This fixes a performance issue which the work laptop is triggering.

Bump resolved version

---

flake.lock
flake.nix
hosts/azathoth/hardware.nix
hosts/carcosa/configuration.nix
hosts/lainonlife/configuration.nix
hosts/lainonlife/hardware.nix
hosts/nyarlathotep/configuration.nix
hosts/nyarlathotep/hardware.nix
shared/concourse/default.nix
shared/default.nix
shared/resolved/default.nix

The only major breaking change is dropping support for PHP 7.4, which is now end-of-life.  So I've had to actually make uzbl-website compatible with PHP 8.
Testing:

Upgrade to NixOS 22.11

---

flake.lock
hosts/nyarlathotep/dashboards/finance.json

I do not need this much cash put aside for household supplies.

[nyarlathotep] Adjust household thresholds on personal finance dashboard

---

shared/default.nix

This is currently a Windows-only system, so it has no NixOS configuration.

Add yog-sothoth SSH key

---

flake.lock
hosts/nyarlathotep/jobs/hledger-fetch-fx-rates.py

This no longer works, and I don't use this data.

[nyarlathotep] Stop tracking LGIMDP prices

---

flake.lock
hosts/nyarlathotep/dashboards/finance.json

e2a5b24 stopped collecting this data

[nyarlathotep] Remove LGIMDP from finance dashboard

---

flake.lock
flake.nix
hosts/nyarlathotep/configuration.nix
packages/prometheus-awair-exporter/default.nix
packages/resolved/default.nix
scripts/lint.sh
shared/resolved/default.nix

This makes packages available as flake outputs.

Define packages at the top level

---

hosts/nyarlathotep/configuration.nix
scripts/lint.sh
shared/backups/default.nix

This creates the timer units automatically.

Use `startAt` instead of `OnCalendar`

---

hosts/nyarlathotep/jobs/bookdb-sync.sh
shared/bookdb/default.nix

See https://github.com/barrucadu/bookdb/pull/175

Update bookdb dump / restore commands

---

hosts/nyarlathotep/jobs/bookmarks-sync.sh
shared/bookmarks/default.nix

See https://github.com/barrucadu/bookmarks/pull/446

Update bookmarks dump / restore commands

---

hosts/azathoth/configuration.nix
hosts/carcosa/configuration.nix
shared/default.nix

These don't need to be system-wide.

Move some packages into user config

---

hosts/carcosa/caddy/memo-barrucadu-co-uk.caddyfile
hosts/carcosa/configuration.nix

Note: `respond PATH STATUS` doesn't work with the `handle_errors` directive, `error PATH STATUS` must be used instead.

[carcosa] Remove some more memos

---

flake.lock
packages/bookdb/default.nix
shared/bookdb/default.nix
shared/bookdb/uuids.yaml

Also remove the "Hull" location since there are no books there any more.

Import bookdb config file

---

flake.lock
packages/bookdb/default.nix

https://github.com/barrucadu/bookdb/pull/182

Bump flake.lock and bookdb

---

packages/bookdb/default.nix

https://github.com/barrucadu/bookdb/pull/188

Bump bookdb

---

flake.lock
hosts/nyarlathotep/configuration.nix

Occasionally a torrent will complain about this, and I have to stop and
start the torrent to fix the bad chunks.

[nyarlathotep] Enable safe_sync for rtorrent

---

hosts/carcosa/configuration.nix

[carcosa] Fix uzbl.org/atom.xml

---

flake.lock
hosts/carcosa/configuration.nix

This enables logging for all the vhosts; though I'm not persisting these
logfiles across reboots at the moment.

[carcosa] Switch to structured caddy config

---

flake.lock
hosts/nyarlathotep/dashboards/finance.json
hosts/nyarlathotep/dashboards/smart-home.json
shared/dashboards/container-stats-detailed.json
shared/dashboards/node-stats-detailed.json
shared/resolved/dashboard.json

[nyarlathotep] Add Owlbear Rodeo panel to budget dashboard

---

flake.lock
packages/resolved/default.nix

Fixes a potential DoS issue[1]
[1] https://github.com/barrucadu/resolved/pull/247

Bump resolved

---

flake.lock
flake.nix
hosts/carcosa/configuration.nix
hosts/nyarlathotep/jobs/hledger-fetch-fx-rates.py
scripts/lint.sh
shared/default.nix

There are no significant breaking changes to worry about this time.
https://nixos.org/manual/nixos/unstable/release-notes.html#sec-release-23.05
Testing:

Upgrade to NixOS 23.05

---

flake.lock
flake.nix

Reverts #207 - docker seems to be working fine now.

Unpin nixpkgs

---

hosts/carcosa/configuration.nix
hosts/nyarlathotep/configuration.nix
shared/default.nix

This is a high number in the user ports range, unlikely to clash with anything else.

Set docker registry port to 46453

---

shared/backups/default.nix
shared/default.nix
shared/oci-containers/default.nix

I think in principle just switching to podman will work now (caveat: need to pass the "insecure-registry" flag to the container rather than the daemon, for nyarlathotep).  But in practice I expect some containers or scripts to break.

Conditionalise all references to docker / podman

---

hosts/nyarlathotep/configuration.nix
shared/concourse/default.nix
shared/default.nix
shared/oci-containers/default.nix
shared/pleroma/default.nix
shared/umami/default.nix

All of the containers are still running as root, so the next step is to set up different users for all these & transfer the file ownership.

[carcosa] Switch to podman

---

hosts/carcosa/configuration.nix
hosts/nyarlathotep/configuration.nix
shared/concourse/default.nix
shared/default.nix
shared/finder/default.nix
shared/foundryvtt/default.nix
shared/pleroma/default.nix
shared/umami/default.nix

This gives all services ports high in the user ports range, unlikely to clash with anything else.

Do away with host-specific service port configuration

---

hosts/nyarlathotep/configuration.nix
shared/concourse/default.nix
shared/finder/default.nix
shared/oci-containers/default.nix

This means the same hostnames can be used for docker and podman.

Fix container hostnames under podman

---

packages/resolved/default.nix
shared/resolved/dashboard.json

This new version fixes NXDOMAIN / NODATA responses (previously most such instances would instead return ServFail), and adds a metric for why queries have been refused.

Bump resolved & add "refused" to dashboard

---

flake.lock
flake.nix
packages/bookdb/default.nix
packages/bookmarks/default.nix
packages/prometheus-awair-exporter/default.nix
packages/resolved/default.nix

Also bring in poetry2nix as a flake so I get a newer version than what's in nixpkgs, and can simplify the bookdb / bookmarks package definitions.

Upgrade all packages

---

shared/umami/options.nix

This has been manually applied to carcosa.

Upgrade umami to postgres 16

---

shared/pleroma/options.nix

This has been manually applied to carcosa.

Upgrade pleroma to postgres 16

---

flake.lock
flake.nix

And temporarily pin the `poetry2nix` dependency to fix a build error.

Bump flake.lock

---

hosts/azathoth/configuration.nix
hosts/nyarlathotep/configuration.nix
hosts/nyarlathotep/jobs/backup-share.py

I never use this, and have deleted the files.

Remove `images` share

---

shared/bookdb/uuids.yaml

I have decided to get rid of these books.

[bookdb] Remove Penguin Little Black Classics

---

flake.lock
hosts/nyarlathotep/dashboards/finance.json

I've started putting excess budget in different accounts to benefit from
better interest rates, so the dashboard needs to combine those to work
out the true amount.

[nyarlathotep] Aggregate budget accounts in gauges

---

shared/umami/default.nix
shared/umami/options.nix

This is a prerequisite to upgrading to v2.

Bump umami to v1.40

---

hosts/nyarlathotep/configuration.nix

This is to stop it breaking CI every other day.

Pin StevenBlack/hosts

---

flake.lock
flake.nix
hosts/carcosa/configuration.nix
hosts/nyarlathotep/configuration.nix
hosts/nyarlathotep/secrets.yaml
packages/bookmarks/default.nix
shared/bookmarks/default.nix
shared/bookmarks/options.nix

This also removes the dependency on `poetry2nix`.

Switch to rust bookmarks

---

docs/src/runbooks/set-up-a-new-host.md
tools/provision-machine.sh

This is intended to be run from within the installation iso.

Add a script to provision a new machine

---

hosts/nyarlathotep/configuration.nix

This just serves a compiled next.js asset bundle.

[nyarlathotep] Add rpg-tools subdomain

---

flake.lock
flake.nix
hosts/carcosa/configuration.nix
hosts/nyarlathotep/configuration.nix
shared/bookdb/default.nix
shared/bookmarks/default.nix
shared/default.nix
shared/pleroma/default.nix
shared/resolved/default.nix
shared/rtorrent/default.nix
tools/provision-machine.sh

No major breaking changes this time.
https://nixos.org/blog/announcements/2024/nixos-2405/
---
Tested on:

Upgrade to NixOS 24.05

---

shared/pleroma/default.nix

This is needed for the containers.

Create /var/run/pleroma/db automatically

---

hosts/nyarlathotep/configuration.nix
hosts/nyarlathotep/jobs/rss-to-mastodon.py
hosts/nyarlathotep/secrets.yaml

https://hacksrus.xyz/users/kjpbot
https://kingjamesprogramming.tumblr.com/

[nyarlathotep] Add job to post KJP to the fediverse

---

hosts/nyarlathotep/configuration.nix
hosts/nyarlathotep/jobs/rss-to-mastodon.py

tumblr truncates the title: https://hacksrus.xyz/notice/Alj49cnMAXJLmAUYKm
I don't think I need to impose my own length limit here, as KJP posts are pretty short.

[nyarlathotep] Use summary for kjp-to-hacksrus, not title

---

shared/bookdb/uuids.yaml

- Split "History" out of "Politics, Philosophy, Economics, + History"
- Collapse "Religion, Mythology, + Folklore" subcategories
- Move "RPG" to top level
- Add new "RPG" subcategories

Shuffle around bookdb categories

---

docs/src/runbooks/set-up-a-new-host.md
hosts/yuggoth/hardware.nix

Also update the documentation so I don't forget this the next time.

[yuggoth] Fix /persist not being available for sops

---

shared/host-templates/website-mirror/resources/www-barrucadu-co-uk.caddyfile

https://github.com/barrucadu/barrucadu.co.uk/commit/400f7c761a74883995d509638bd1b973f7c4dd5c

Remove gone response for barrucadu.co.uk/sitemap.xml

---

hosts/nyarlathotep/jobs/hledger-export-to-victoriametrics.py

VictoriaMetrics only allows data up to 2 days in the future, which is a pain for forecasting (am I cursed to be unable to find a timeseries database that meets all my wants at once?).  So implement a work-around: an optional env var specifying an integral number of years to shift data back in time by.
Then if I want to, say, forecast up to the end of the year I run this with `YEAR_OFFSET=1` and see that as up to the end of *last* year.

[nyarlathotep] Implement workaround to forecast finances

---

shared/host-templates/website-mirror/default.nix

This is so I can go to `bookdb.carcosa.barrucadu.co.uk` / `bookdb.yuggoth.barrucadu.co.uk` to bypass the GeoDNS.

[website-mirror] Add prefixed subdomains of all sites

---

shared/bookdb/default.nix
shared/bookmarks/default.nix
shared/concourse/default.nix
shared/finder/default.nix
shared/pleroma/default.nix
shared/umami/default.nix

dockerhub is introducing very aggressive rate limiting shortly.

Pull docker images from mirror.gcr.io

---

shared/bookdb/uuids.yaml

Add "Packed" location to bookdb

---

flake.lock
flake.nix
hosts/carcosa/secrets.yaml
hosts/nyarlathotep/configuration.nix
hosts/yuggoth/secrets.yaml
shared/default.nix
shared/erase-your-darlings/default.nix
shared/pleroma/default.nix
shared/torrents/default.nix

Apparently I just forgot to do this.  After this I'll proceed to NixOS 25.05.

Upgrade to NixOS 24.11

---

hosts/nyarlathotep/configuration.nix
hosts/nyarlathotep/dashboards/smart-home.json

- Plex for the living room audio
- New awairs in the guest bedroom & office
- Tweak the formatting of the smart home dashboard for the extra awairs

[nyarlathotep] Add config for house move

---

hosts/nyarlathotep/dashboards/finance.json

[nyarlathotep] Update TBC estimate in finance dashboard
