hosts/dunwich/commento.docker-compose.nix
hosts/dunwich/configuration.nix
hosts/dunwich/umami.docker-compose.nix

I ran `docker volume prune` and it deleted a bunch of volumes which
were in use:
- pleroma database (but not emojis or uploads)
- bookdb covers (but not esdata)
- bookmarks esdata
- umami database
- commento database
But all of the services were up and running, and using those volumes!
So somehow despite the volumes being in use, they got deleted.  wtf?

[dunwich] Use directories for persistent docker volumes

---

hosts/carcosa/configuration.nix
services/concourse.nix
services/docker-compose-files/concourse.docker-compose.nix

I had to stop using the `quickstart` command when I migrated Concourse to carcosa (2bb1684b482972e95ff11409458f4acde304a5cf), because:
1. Concourse workers don't get on with ZFS (https://github.com/concourse/concourse-docker/issues/42)
2. But that's ok, there's an environment variable to use a different directory
3. But that environment variable only works with the `worker` command, not the `quickstart` command
Unfortunately, there was an unforeseen downside to this change.  When running separate `web` and `worker` processes, a "stalled" worker (which is what happens after, eg, restarting the docker-compose project) doesn't get deleted automatically, and so any volumes which belong to the old worker won't get garbage collected.  Resulting in a disk space leak.
After a few restarts I ended …

Improve concourse monitoring & run worker as "ephemeral" to fix volume leak

---

hosts/carcosa/configuration.nix
hosts/carcosa/grafana-dashboards/overview.json

This dashboard has already paid off, as it was while making this that
I noticed the unusually high disk usage by Concourse (#12).
I think this is a pretty good dashboard which could potentially become
a template for other machines, as it only uses the node and docker
exporters.  It does, however, have knowledge of how mountpoints are
allocated to partitions, and what alerts are appropriate.  So it's not
fully generic.
---
The main part of the dashboard fits on a single screen:
There's also a (collapsed by default) row for the alert configuration just off the bottom:

[carcosa] Add grafana dashboard

---

common.nix
hosts/nyarlathotep/configuration.nix
services/snippets/docker-compose-service.nix

`After`, `BindsTo`, and `Requires` all do slightly different things:
`After` imposes an ordering constraint.  If unit `X` has `After=Y` and
both `X` and `Y` are started, then `X` will be delayed until `Y` has
finished starting.
So we want `After=docker.service`, as `docker` and `docker-compose`
won't work if the daemon is not up yet.
`BindsTo` and `Requires` impose dependencies.  If a unit `X` has
`BindsTo=Y` or `Requires=Y`, and `X` is started then `Y` will be
started if it not already running.
Combining `Requires=Y` (or `BindsTo=Y`) and `After=Y` means that
starting `X` will
- Start `Y`
- Wait for `Y` to finish starting
- Then start `X`
If there is no `After`, then instead `X` and `Y` will be started in
parallel.
`BindsTo` also makes `X` stop if `Y` stops.  This is particularly
useful …

Tighten up docker unit dependencies

---

services/docker-compose-files/bookdb.docker-compose.nix
services/docker-compose-files/bookmarks.docker-compose.nix
services/docker-compose-files/finder.docker-compose.nix
services/minecraft.nix

I gave quite generous memory allocations to Minecraft, bookdb, bookmarks, and finder.  But looking at the actual usage, there's no need to reserve so much.  This change gives carcosa a nice amount of headroom for future developments.

Reduce JVM memory allocations

---

hosts/lainonlife/configuration.nix

This was missed in 24226409201b73fff4609ba1a80201315c09c67a, and
lainon.life hasn't been updated in a while.

[lainon.life] Set pleroma docker volume dir

---

hosts/nyarlathotep/grafana-dashboards/finance.json

There are a few small changes here:
- Layout changes: swapping the "House Deposit" and "Student Loan"
panels; removing two of the row headings so it fits on a single
screen; and renaming the "Economy" heading to "Market Prices".
- Revising the target thresholds: "Long Runway" is now at half a year
/ a year; "Student Loan" is now yellow below 0 as it's not really a
problem.
- Updating the "Investments" pie chart: removing "Cryptocurrency" and
"Innovative Finance ISA" and adding "S&S LISA".
And one larger change, fixing an error in calculation in the
Short/Long Runway metrics, which were including gross expenses (things
taken out of my gross salary like income tax or pension contributions)
in the average daily expense calculation.  With that error fixed, my
runways are looking much …

[nyarlathotep] Update personal finance dashboard

---

hosts/nyarlathotep/grafana-dashboards/finance.json

I spent £2k to move to my current flat, which covered cost of
moving (£300) + buying a load of new furniture (the rest).
I now have more furniture, so moving will be more expensive when I
next do it.  But moving existing furniture is necessarily cheaper than
moving a minimal amount of stuff and replacing all the furniture;
otherwise people would do that.
So saving over twice the amount I paid is kind of ridiculous.

[nyarlathotep] Revise "move" budget target

---

common.nix

I've spent a good chunk of time today wondering "hmm, why have all my
servers auto-downgraded themselves overnight?"

Specify 21.05 as the auto-upgrade channel

---

services/minecraft.nix

Missed in the 21.05 upgrade notes:
> jre now defaults to GTK UI by default. This improves visual
> consistency and makes Java follow system font style, improving the
> situation on HighDPI displays. This has a cost of increased closure
> size; for server and other headless workloads it's recommended to
> use jre_headless.
Also, the Minecraft server I currently have assumes Java 8 and crashes
when run with a later version.  So much for the legendary backwards
compatibility of Java.

Use headless JRE 8 for minecraft

---

services/concourse.nix

After a recent reboot, Concourse stopped working.  The culprit seems
to be a cgroup issue as described in the linked GitHub issue (see
diff), so it's likely a systemd or kernel upgrade which broke it.
Since everything else is otherwise working fine, this is better than
rolling back to an older generation.

Fix Concourse cgroup issue

---

services/docker-compose-files/concourse.docker-compose.nix

Unfortunately, there's a DNS resolution issue with this: sometimes,
when using the default resolver (which I believe comes from docker, as
it's on a 172 IP), names fail to resolve, which generally makes a job
fail.
So, skip the local DNS resolution entirely and use 1.1.1.1, falling
back to 8.8.8.8 if it's down.  So far this looks to solve the issue.

Upgrade Concourse to 7.4

---

hosts/nyarlathotep/grafana-dashboards/finance.json

A stacked area chart + a single pie chart is more useful as an
overview, as it shows how much of my assets belong to each class over
time (a stacked percentage chart would do both in the same graph, but
would no longer show the total, which is less helpful).  If I want
more detail I can always drill down manually with hledger.

[nyarlathotep] Replace asset / cash / investment allocation charts

---

hosts/nyarlathotep/grafana-dashboards/finance.json

I've started tracking my Civil Service pension.  It's defined-benefit, so I'm using `£/yr` as a commodity.  Based on the 4% rule, I've gone for `1 £/yr == £25`

[nyarlathotep] Add FIRE numbers to finances dashboard

---

hosts/nyarlathotep/grafana-dashboards/finance.json

Adds `$average_daily_expense`, `$fire_annual_factor`, and
`$fire_invested` to simplify the FIRE and runway calculations.
The `$fire_annual_factor` is 1 / SWR: the number of years expenses you
need saved to be able to safely withdraw one year's expenses
annually.  This is 25, as I'm using the 4% rule.
Not sure why, but the generated dashboard JSON downgrades a bunch of
components.  There isn't an obvious visual impact of this...
This commit also fixes a couple of unintentional changes introduced by
d50631d: changing the default time period to 2 years, and expanding
the market prices row.

[nyarlathotep] Use variables to simplify dashboard & add FIRE deltas

---

hosts/nyarlathotep/grafana-dashboards/finance.json

- Drop general emergency fund: I already have 3+ months expenses in
cash, and a credit card, and general-purpose floats.  It's hard to
imagine what would come up which couldn't be solved by reallocating
money from those.
- Reduce float to £250/bank: if I need more than that, I need to
adjust the budget.
- Reduce move fund to £1000: this is likely still too high, given I'm
not likely to move for a while, but it could happen that I'm suddenly
served an eviction notice and need to move out.
I'll invest as a lump sum the excess money that was in those
categories.

[nyarlathotep] Adjust budget goals

---

hosts/carcosa/configuration.nix

NixOS 21.11 changed the default PHP version to 8, which the old
uzbl.org code does not support.

[carcosa] Use PHP 7.4 for uzbl.org

---

hosts/nyarlathotep/grafana-dashboards/finance.json

I think this graph is better: it's more or less ordered by stability,
with receivables (which almost never change) at the bottom,
cash (which changes a lot) at the top, and investments in the middle.

[nyarlathotep] Re-order assets

---

common.nix
configuration.nix
hosts/azathoth/configuration.nix
hosts/carcosa/configuration.nix
hosts/lainonlife/configuration.nix
hosts/nyarlathotep/configuration.nix
modules/firewall.nix

There are a lot of connection attempts to my whitelisted Minecraft
server.  I occasionally check the Minecraft logs, and it's kind of
annoying having to mentally filter through these.  Since they come
from a handful of IPs, it's nice to have a way to block them.
This is done with a new iptables chain, put before the nixos-fw chain,
which just either drops a connection if it's on the naughty list, or
returns to the INPUT chain.
I only really need this on carcosa, because that's where the affected
service is, but there's no reason not to make this a module which all
hosts pull in.
And, since I'm adding one sort of blocking, I thought I may as well
also turn on fail2ban, which will (by default) block SSH connection
attempts.

Add firewall module with fail2ban and ip blocking

---

services/bookdb.nix
services/bookmarks.nix
services/finder.nix

This is a prerequisite for upgrading to 8.0.0, going straight from
7.11 isn't allowed:
java.lang.IllegalStateException: cannot upgrade a node from
version [7.11.2] directly to version [8.0.0], upgrade to version
[7.17.0] first.

Upgrade services to elasticsearch 7.17.0

---

services/bookdb.nix
services/bookmarks.nix
services/finder.nix

This also explicitly disables security, as security is enabled by
default in 8+.  Since the ES instances are only exposed to localhost,
this is fine for now.

Upgrade services to elasticsearch 8.0.0

---

configuration.nix
hosts/nyarlathotep/configuration.nix
modules/erase-your-darlings.nix
services/pihole.nix

My Raspberry Pi has died - presumably SD card failure.  I don't have a spare SD card, and running this weird pet Debian server is something I've wanted to stop doing for a while, so I've decided to move DNS onto NixOS instead.
This isn't a perfect configuration-as-code solution, I still need to manually block or allow things through the Pi Hole web interface, and configure custom records through the dnsmasq config files, but at least that's now a small contained amount of state I can easily back up.  Ideally, though, everything would be done through configuration.

Add Pi Hole service & enable on nyarlathotep

---

services/pihole.nix

If there are other docker containers running on the same host, and the
host resolves DNS via the Pi Hole, then those other containers are
unable to resolve DNS.  Specifically, they get a failure in name
resolution due to the response coming back from an unexpected IP.
The solution is to bind to the external IP only, not to all
interfaces.  Note that this now rules out the `onlyLocalDNS` option.

Bind Pi Hole to server IP, not 0.0.0.0

---

services/pihole.nix

This is also needed to totally solve the docker issue described in
37f3dca.

Open port 53 (TCP and UDP) for Pi Hole

---

hosts/azathoth/configuration.nix
hosts/nyarlathotep/configuration.nix

This defeats the point of configuring a firewall; though neither of those machines are exposed to the internet so it doesn't really matter.
I'm also tempted to remove
```nix
networking.firewall.trustedInterfaces = if config.virtualisation.docker.enable then [ "docker0" ] else [ ];
```
From the firewall module, but would need to think about how to test this is safe first.

Remove `trustedInterfaces` from nyarlathotep & azathoth

---

hosts/nyarlathotep/configuration.nix

I got tripped up by these because (1) I did manually check Samba, but
Windows had the directory listings and file contents cached for all
the things I quickly looked at, so everything kept working; and (2)
NixOS services are very inconsistent over whether they open firewall
ports automatically or not.

[nyarlathotep] Open NFS & Samba ports

---

modules/erase-your-darlings.nix

Remove trailing reference to `services.pihole`

---

hosts/nyarlathotep/configuration.nix
services/resolved.nix

This fixes several issues:
- A memory leak where the zones get cloned on every request
- Incorrect handling of `CNAME`d and delegated non-recursive results
- Inconsistent behaviour of non-authoritative records with the cache
- Not sending wildcard queries upstream
- Failing to parse one entry of the StevenBlack hosts list
And adds some new features
- Reloading the configuration on SIGUSR1
- A CLI argument to set the cache size

Upgrade to latest version of resolved

---

hosts/carcosa/configuration.nix
hosts/nyarlathotep/configuration.nix
modules/erase-your-darlings.nix

While `/var/log` is preserved, journalctl can't actually access logs
from previous boots easily.  It only sees the current boot:
$ journalctl --list-boots
0 5ee8929892ac4b9fb3d4bcee29039c66 Sat 2022-04-02 12:55:06 BST—Sat 2022-04-02 13:14:42 BST
This is because it uses `/etc/machine-id` to identify which logs
belong to this machine, and so if that changes, the old logs exist but
can't easily be accessed.
Note: machine-id(5) says:
> This ID uniquely identifies the host. It should be considered
> "confidential", and must not be exposed in untrusted environments,
> in particular on the network.
And yet here I am committing it to a public git repository.  As far as
I can tell this is a privacy consideration, like MAC address exposure,
and not a security consideration.  So I don't think …

Set /etc/machine-id in erase-your-darlings mode

---

services/resolved.nix

systemd recommends this approach over `User=nobody`[1]
[1] https://www.freedesktop.org/software/systemd/man/systemd.exec.html

Use `DynamicUser=true` for resolved unit

---

modules/erase-your-darlings.nix

It's not clear from the systemd documentation[1] that this will work,
but I've tested it by stopping prometheus, unmounting the bind-mount,
rebuilding the configuration, starting prometheus, and seeing that new
metrics appear and old metrics are still available.
[1] https://www.freedesktop.org/software/systemd/man/systemd.exec.html

Use `BindPaths` for Prometheus unit state dir

---

modules/erase-your-darlings.nix

This was originally added so I could use a pie chart plugin, but
grafana has long had its own pie chart panel type now.

Remove grafana override for erase-your-darlings

---

common.nix

This is safe to do, because none of the changes affect me.
Here are all mentions of the `stateVersion` in the release notes since
17.03.
**NixOS 21.11:**
No mentions.
**NixOS 21.05:**
- CodiMD has been renamed to HedgeDoc, and associated suernames and
directories have been renamed.  I don't use CodiMD.
- Radicale no longer uses the state version to determine package
version.  I don't use Radicale.
**NixOS 20.09:**
- Supybot uses a different state directory and has some different
systemd sandboxing options.  I don't use Supybot.
- Deluge uses the state version to determine package version.  I don't
use Deluge.
- Postgres no longer uses state version to determine data directory
location.  I do use Postgres, but not the NixOS package: only
dockerised.
- Jellyfin uses the state version to …

Bump `system.stateVersion` to 21.11

---

hosts/carcosa/configuration.nix

I'm looking into Foundry VTT as a replacement for Roll20.  I've been paying for a Roll20 pro membership for 8 or 9 months now, just so I can use custom character sheets for Traveller.  But Foundry has a pretty good looking unofficial Traveller system, which I should try out.

[carcosa] Add a Foundry VTT service

---

common.nix
flake.lock

This is no longer necessary now that I've moved to sops-nix for
secrets and moved the lainonlife pleroma favicon into a subdirectory.

Remove `--impure` flag from auto-upgrade task

---

hosts/nyarlathotep/grafana-dashboards/smart-home.json

Expand the time range to 12 hours by default (30m is nice to see the
immediate state and short-term change, but I find myself more often
wanting a longer view).
Also remove the hard-coded graph axis ranges.  I had those to show the
bad thresholds, but in practice it makes small or gradual changes
harder to see.

[nyarlathotep] Expand smart home dashboard range & change graph axes

---

modules/zfs-automation.nix

I noticed that these snapshots were using up a huge amount of disk
space on nyarlathotep and carcosa, to the extend of causing problems
for other things (eg, taking a full backup resulting in running out of
disk space)

Reduce number of zfs monthly snapshots to 3

---

common.nix
hosts/carcosa/configuration.nix
modules/erase-your-darlings.nix
services/foundryvtt.nix

Foundry's got a few different bits of config now, so move it all to a
new file (even though it's only used by carcosa).
This relies on the Foundry files being in the right place.  Since
Foundry is nonfree software which has to be downloaded from the online
store after purchase, that seems unavoidable.

Add a service file for Foundry

---

common.nix
hosts/carcosa/configuration.nix
hosts/carcosa/secrets.yaml
hosts/nyarlathotep/configuration.nix
hosts/nyarlathotep/secrets.yaml
modules/monitoring-scripts.nix
modules/zfs-automation.nix
services/monitoring.nix

This PR does for my monitoring-scripts repository what #109 and #114 did for my backup-scripts repository: pull it into this repo, improve it, and fully retire the old repo.

Import monitoring-scripts & rename to `services.monitoring`

---

flake.lock
hosts/nyarlathotep/configuration.nix
hosts/nyarlathotep/secrets.yaml

Previously, this was done by unmanaged (but backed-up) files in
`/persist`.  But now that the default config is taken straight from
the resolved source (5ab0007), only the custom config needs to be
managed.
Custom zones I've added to the secrets (though it's more "private"
than "secret") and the StevenBlack blocklist I just fetch from the
source.  Yes, this does impose a new external dependency on this repo,
but the chances of it disappearing seem pretty slim, and I can just
remove it if that does happen.  The alternative was committing ~6MB of
hosts file, which felt a bit excessive.

[nyarlathotep] Import DNS config

---

common.nix
modules/erase-your-darlings.nix

Need to set the `system.autoUpgrade.flake` parameter, or it tries to
use the old CLI.
Yes, this has been broken since July - I've just been occasionally
updating my systems by hand since then.

Fix auto-upgrades

---

.github/workflows/ci.yaml
flake.nix

This ensures I have the same version of the formatter locally and in CI, which has caused problems before.

Use `nix fmt`

---

shared/pleroma/default.nix

This is so it's possible to run a `VACUUM ANALYZE` from time to time.
Possible future work: add a maintenance task to do that.

Increase pleroma postgres `/dev/shm` size

---

flake.lock
flake.nix
hosts/carcosa/configuration.nix
hosts/lainonlife/configuration.nix
hosts/nyarlathotep/configuration.nix
scripts/lint.sh
shared/bookdb/default.nix
shared/bookmarks/default.nix
shared/concourse/default.nix
shared/default.nix
shared/erase-your-darlings/default.nix
shared/finder/default.nix
shared/oci-containers/default.nix
shared/pleroma/default.nix
shared/umami/default.nix
shared/wikijs/default.nix

Adds a few useful behaviours.
Config:
- Auto-start
- Add param to join network
- Map named volumes to filesystem mounts
- Bind all ports to `127.0.0.1`
Pre-start:
- Pull the image (useful for `:latest` images)
- Create the network

Add an abstraction over raw oci-containers

---

scripts/backups.sh

This script is just used for checking the status of and restoring backups, not taking them, so things have been getting backed up as they should.

Fix backups secrets name in utility script

---

flake.nix
shared/backups/default.nix

This isn't needed, the package now depends on boto3 by default.

Remove boto3 from duplicity PYTHONPATH

---

hosts/lainonlife/configuration.nix
hosts/nyarlathotep/configuration.nix

This removes the need to set the `PYTHONPATH` env var.

Replace `python3.buildEnv` with `python3.withPackages`

---

flake.nix

`writeShellScriptBin` takes care of the shebang, and also `makeBinPath` simplifies the PATH variable.

Simplify flake scripts

---

.github/workflows/ci.yaml
README.markdown
flake.nix
hosts/nyarlathotep/jobs/backup-share.py
scripts/fmt.sh
scripts/lint.sh

This adds a new `nix run .#fmt` script, which differs from `nix fmt`: `nix fmt` is just for formatting `*.nix` files, so I thought it would be confusing to make it format non-nix code too.

Format and lint python scripts

---

flake.lock
hosts/nyarlathotep/dashboards/finance.json

The major change is that the FIRE & savings panels now exclude pension
contributions, since having a good pension doesn't help me
retire *early*.

[nyarlathotep] Finance dashboard tweaks 

---

flake.lock
flake.nix
hosts/lainonlife/configuration.nix
hosts/lainonlife/secrets.yaml
shared/erase-your-darlings/default.nix
shared/foundryvtt/default.nix
shared/foundryvtt/erase-your-darlings.nix
shared/minecraft/default.nix
shared/minecraft/erase-your-darlings.nix
shared/pleroma/default.nix
shared/pleroma/erase-your-darlings.nix

The standard Pleroma module is good enough, and means I don't need to build my own containers from the develop branch - which isn't a supported approach anyway and frequently breaks.
I need to use the Pleroma from nixpkgs-unstable because my current image is based on 2.5, but nixpkgs only has 2.4, which isn't compatible due to database changes.
The database is still dockerised, so it's not subject to the whims of `system.stateVersion`.
I've also changed the backup script to use the custom pgdump format, because that can be restored in parallel.  A test run only took 90 minutes (plus another 9 minutes to run a `VACUUM ANALYZE`), which is much better than the 3 *days* it took when I last had to restore a SQL dump.

Switch to standard Pleroma module

---

hosts/carcosa/configuration.nix

This was the gitea SSH port, but I stopped using gitea in 2022.

[carcosa] Do not open port 222

---

flake.nix
hosts/azathoth/configuration.nix
hosts/carcosa/configuration.nix
hosts/lainonlife/configuration.nix
hosts/nyarlathotep/configuration.nix

This needs to be kept in sync between both places, so just define it in one.

Set `networking.hostName` in flake.nix

---

flake.nix
hosts/carcosa/configuration.nix
hosts/lainonlife/configuration.nix
hosts/nyarlathotep/configuration.nix

Previously, enabling secrets on a host required updating two files: enabling the module in flake.nix and setting a default file in the host configuration.  This commit puts all that in one place.

Set `sops.defaultSopsFile` in flake.nix

---

flake.nix
hosts/carcosa/configuration.nix
hosts/nyarlathotep/configuration.nix
hosts/nyarlathotep/jobs/bookmarks-sync.sh
packages/bookmarks/default.nix
shared/bookmarks/default.nix

Natively packaging this application isn't very hard.  It does make the sync script a little more complex, as it's got to work out the appropriate path to the python environment, but that's not too tricky.
This also makes deploying updates to nyarlathotep a little easier: I don't need to build a docker image, push it to a local repo, and restart the service any more.  I just bump the version in the package, same as resolved and prometheus-awair-exporter.
Needing to expose the Elasticsearch instance to localhost is a bit unfortunate, however.  Maybe I'll be able to do some systemd network namespacing magic and lock that down at some point.
I also changed the bookdb port to be a random one in the high end of the user ports range which is unlikely to clash with anything else.

Run bookmarks outside of docker

---

flake.nix
hosts/carcosa/configuration.nix
hosts/carcosa/secrets.yaml
hosts/nyarlathotep/configuration.nix
packages/bookdb/default.nix
shared/bookdb/default.nix
shared/bookdb/erase-your-darlings.nix

Natively packaging this application isn't very hard.  It does make the sync and backup scripts a little more complex, as they now need to handle retrieving files owned by the bookdb user, but that's not too tricky.
This also makes deploying updates to nyarlathotep a little easier: I don't need to build a docker image, push it to a local repo, and restart the service any more.  I just bump the version in the package, same as bookmarks, resolved, and prometheus-awair-exporter.
Needing to expose the Elasticsearch instance to localhost is a bit unfortunate, however.  Maybe I'll be able to do some systemd network namespacing magic and lock that down at some point.
I also changed the bookdb port to be a random one in the high end of the user ports range which is unlikely to clash with anything …

Run bookdb outside of docker

---

hosts/carcosa/configuration.nix

Incorrectly removed in fd2f334.
This is of course still needed to deploy the static sites.

[carcosa] Bring back concourse-deploy-robot user

---

hosts/nyarlathotep/configuration.nix

These occasionally collide right now.  Usually that makes the backup fail (since the collision tends to be with the bookdb cover files changing while the backup `tar` is running, which throws an error), but if it happened during the elasticsearch index sync I could end up backing up incomplete data.
Another option would be adding some sort of lockfile which prevents both running at the same time, but this is simpler.

[nyarlathotep] Offset sync from backup schedule

---

flake.lock
flake.nix

https://github.com/NixOS/nixpkgs/issues/244159
This suggests a fix has been backported to 23.05, but since this morning's auto-update, and with an up-to-date system I'm unable to start docker containers.

Temporarily pin nixpkgs-23.05

---

hosts/carcosa/configuration.nix
hosts/nyarlathotep/configuration.nix
shared/default.nix

There's no need to enable this per-host, since I always want these.

Always enable deletion and garbage collection for docker registries

---

hosts/nyarlathotep/configuration.nix
shared/concourse/default.nix
shared/finder/default.nix
shared/oci-containers/default.nix
shared/umami/default.nix

To migrate to podman I want my oci-containers lib to do all the heavy lifting.  Ideally, I'll be able to switch back and forth between podman and docker on a single host without breaking anything.
As part of that, add a 'pod' abstraction which groups containers together.  All containers in a pod share the same `volumeSubDir`.
With docker, pods are faked by putting the containers onto the same network.  But with podman they're true pods.

Make pods a first-class citizen for OCI containers

---

hosts/nyarlathotep/configuration.nix
shared/default.nix
shared/rtorrent/default.nix
shared/rtorrent/erase-your-darlings.nix

This bundles together the firewall options, rtorrent systemd unit, and flood systemd unit.  It also has the unit use the normal directories under /var for state and logs.
Unfortunately, /dev/stdout isn't openable so I still have to log to files rather than to the journal.

Add an rtorrent module

---

shared/rtorrent/default.nix

Reduce the default rtorrent logging

---

shared/backups/default.nix
shared/bookdb/default.nix
shared/concourse/default.nix
shared/foundryvtt/default.nix
shared/pleroma/default.nix
shared/umami/default.nix

Firstly, a little refactoring:
- Implicitly `chown` all backup subdirectories in the main script, so each separate script doesn't need to do that manually.
- Add a `nixfiles.backups.sudoRules` option which fills in the user and options automatically.
Then change the bookdb and foundryvtt scripts to be a bit more incremental-friendly by not targz-ing *everything*.

Backup script tweaks

---

docs/src/runbooks/set-up-a-new-host.md
flake.nix

This is fine because the secrets.yaml and sops configuration only needs
to exist if you actually try to use the secrets.

Always include sops configuration 

---

shared/concourse/options.nix

This has been manually applied to carcosa.

Upgrade concourse to postgres 16

---

docs/src/runbooks/upgrade-to-a-new-version-of-postgres.md

postgres uses shm for IPC, so this helps with the performance.

Increase shared memory in postgres upgrade runbook

---

hosts/nyarlathotep/configuration.nix
hosts/nyarlathotep/jobs/tag-podcasts.sh

This is for Ben Laurence's "Into the Megadungeon".

[nyarlathotep] Convert podcast m4a files to mp3

---

hosts/nyarlathotep/jobs/hledger-export-to-promscale.py

The net income calculation on the finance dashboard was broken by the omission of GBP `assets:pension` balances.  Rather than make the dashboard fill in the blanks, I decided to propagate accounts for credits / debits through all times.  This means the finance metrics are now defined for all (account, currency) pairs for all of time, so long as a posting for that currency ever existed, with a default value of 0.

[nyarlathotep] Project accounts across time

---

docs/src/SUMMARY.md
docs/src/runbooks/move-a-configuration-to-a-new-machine.md
docs/src/runbooks/set-up-a-new-host.md

nyarlathotep mysteriously died last week, so I got a bunch of new hardware and redeployed the configuration.  There were some things to figure out.

Add a runbook for migrating to a new machine

---

hosts/carcosa/configuration.nix
hosts/nyarlathotep/configuration.nix
shared/bookdb/default.nix
shared/concourse/default.nix
shared/foundryvtt/default.nix
shared/pleroma/default.nix
shared/umami/default.nix

bookdb-sync mysteriously broke, due to a path changing.  Avoid that, and similar problems, by being explicit about all the paths of sudo-ed things.

Make `sudo` paths explicit

---

shared/umami/options.nix

I have run the data migration script manually, see https://umami.is/docs/migrate-v1-v2

Bump umami to v2.9.0

---

hosts/nyarlathotep/configuration.nix

This PR binds `resolved` to 10.0.0.3 rather than 0.0.0.0, so I can run the thing-doer DNS server on an internal interface.  It also sets up a bridge network to the LAN so I can spin up VMs which get assigned LAN IP addresses.

[nyarlathotep] Netwoking changes for thing-doer

---

shared/oci-containers/default.nix

The NixOS module only enabled the service if there are containers, but that means I have different podman config on azathoth and nyarlathotep, as the former has no containers.  That kind of sucks, so just always enable it.

Enable oci-container backend service always

---

README.markdown

This commit updates the the link from the former, unofficial nixos wiki page to the new https://wiki.nixos.org
ref: NixOS/foundation#113

README.markdown: Link to new NixOS wiki

---

flake.lock
flake.nix

With the newest rust-overlay, bookdb & bookmarks are missing openssl at runtime.

Bump flake.lock & pin oxalica/rust-overlay

---

shared/default.nix

The default behaviour of actual panics and zfs "panics" halting the system aren't very useful to me, since I'm not a kernel developer.  I want the system to just reboot.  An oops is also often not recoverable, so just panic / reboot on those as well.
This is motivated by a few recent zfs "panics" on nyarlathotep:
VERIFY3(sa.sa_magic == SA_MAGIC) failed (8192 == 3100762)
PANIC at zfs_quota.c:88:zpl_get_file_info()
Showing stack for process 411118
CPU: 11 PID: 411118 Comm: nix Tainted: P           O       6.1.92 #1-NixOS
Hardware name: ASUS System Product Name/PRIME B650M-A AX, BIOS 0421 08/19/2022
Call Trace:
<TASK>
dump_stack_lvl+0x44/0x5c
spl_panic+0xf0/0x108 [spl]
? srso_alias_return_thunk+0x5/0x7f
? dnode_cons+0x2a1/0x2c0 [zfs]
zpl_get_file_info+0x227/0x240 [zfs] …

Reboot on panic, oops, and zfs "panic"

---

shared/concourse/default.nix
shared/concourse/options.nix

I need to switch away from cgroupsv1 because podman is dropping support.  The containerd runtime works with cgroupsv2, so I need to switch to that too.

Switch concourse to containerd runtime & drop cgroupsv1

---

docs/src/SUMMARY.md
docs/src/runbooks/alerts/diskspacelow.md
shared/default.nix

I've picked 10% remaining free space as the threshold.

Add an alert and a runbook for low disk space

---

hosts/nyarlathotep/configuration.nix
hosts/nyarlathotep/dashboards/finance.json
hosts/nyarlathotep/jobs/hledger-export-to-victoriametrics.py

Promscale was discontinued early last year, and around the beginning of this year developed the irritating problem of frequently dropping data, which led to me looking at the dashboard less and less often.
I tried using the prometheus backfilling tool, but couldn't get it to work - it apparently loaded everything without error, but the metrics just weren't there.  It also took 10m+ to load my historic hledger data, which is far worse than the few seconds promscale took.
Today I found VictoriaMetrics, which falls into the same sweet spot as promscale: it has an API that supports deleting timeseries and loading data with arbitrary timestamps, and supports the prometheus query language.  It works really well so far, is faster for big queries than promscale was, and I've got my dashboard …

[nyarlathotep] Switch from promscale to VictoriaMetrics

---

hosts/nyarlathotep/configuration.nix

It's not persisted, so it's lost on boot.
5m is too long a delay, it could probably be 1m, but nyarlathotep only reboots in the early hours of the morning so I'm not too concerned with getting the data ASAP.

[nyarlathotep] Load victoriametrics data after boot

---

hosts/carcosa/configuration.nix
hosts/nyarlathotep/configuration.nix
shared/bookdb/default.nix
shared/bookdb/options.nix
shared/bookdb/remote-sync-receive.nix
shared/bookdb/remote-sync-send.nix
shared/bookmarks/default.nix
shared/bookmarks/options.nix
shared/bookmarks/remote-sync-receive.nix
shared/bookmarks/remote-sync-send.nix

Also change the "push" scripts to allow multiple sync targets

Refactor: move bookdb & bookmarks sync scripts into modules

---

hosts/carcosa/configuration.nix
hosts/yuggoth/configuration.nix
hosts/yuggoth/secrets.yaml

This will let me drop yuggoth down to the smallest instance type, as I no longer need to be able to compile bookdb and bookmarks locally.

[carcosa / yuggoth] Configure remote builds

---

shared/bookdb/options.nix
shared/bookmarks/options.nix
shared/concourse/options.nix
shared/erase-your-darlings/options.nix
shared/finder/options.nix
shared/foundryvtt/options.nix
shared/minecraft/options.nix
shared/oci-containers/options.nix
shared/options.nix
shared/pleroma/options.nix
shared/resolved/options.nix
shared/restic-backups/options.nix
shared/torrents/options.nix
shared/umami/options.nix

Documentation is markdown by default now.

Remove uses of deprecated `mdDoc`

---

shared/bookdb/default.nix
shared/bookmarks/default.nix

They each have under 100MiB of data, it'd be more efficient at this rate to stick the data in a single large JSON file.

Reduce bookdb & bookmarks memory to 256MiB

---

shared/bookdb/remote-sync-send.nix

The etag is derived from the mtime, so this keeps them consistent unless the image actually changes.

Preserve timestamps in bookdb sync

---

flake.lock
flake.nix

Both latest resolved & latest sops-nix need nixpkgs-unstable to build at the moment, for newer go & rustc.

Bump flake.lock

---

docs/src/SUMMARY.md
docs/src/runbooks/upgrade-to-a-new-version-of-elasticsearch.md
shared/bookdb/options.nix
shared/bookmarks/options.nix
shared/finder/options.nix

This is the latest minor version in the 8.x series, preparation for upgrading to 9.0.0.

Upgrade elasticsearch to 8.18.2 

---

shared/default.nix

Very handy for diagnosing network issues.

Add `mtr` to default packages
